_schema-version: '3.2'
ID: nuam-react-auditoria-standalone
version: 0.0.1
description: "NUAM Auditoria Frontend (React Standalone) - QAS"

parameters:
  enable-parallel-deployments: true

build-parameters:
  before-all: []

modules:
  - name: nuam-react-auditoria-app
    type: html5
    path: .
    build-parameters:
      builder: custom
      build-result: dist
      supported-platforms: []
      commands: [] # Build done in deploy.sh

  - name: nuam-auditoria-deployer
    type: com.sap.application.content
    path: .
    requires:
      - name: xsuaa-central
      - name: nuam-html5-repo-host
        parameters:
          content-target: true
    build-parameters:
      build-result: resources
      requires:
        - name: nuam-react-auditoria-app
          artifacts:
            - dist.zip
          target-path: resources

resources:
  - name: nuam-html5-repo-host
    type: org.cloudfoundry.existing-service
    parameters:
      service-name: nuam-html5-repo-host

  - name: xsuaa-central
    type: org.cloudfoundry.existing-service
    parameters:
      service-name: xsuaa-central

  - name: nuam-destination-service
    type: org.cloudfoundry.existing-service
    parameters:
      service-name: nuam-destination-service
